version: "3"
networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.17.0/24
  cloud:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/16
services:
  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
  client:
    build:
      dockerfile:
        client/Dockerfile
    networks:
      local:
        ipv4_address: 192.168.17.20
    depends_on:
      - server
  fwd:
    build:
      dockerfile:
        fwd/Dockerfile
    networks:
      local:
        ipv4_address: 192.168.17.10
      cloud:
        ipv4_address: 172.30.1.1
    depends_on:
      - server    
  server:
    build:
      dockerfile:
        server/Dockerfile
    networks:
      cloud:
        ipv4_address: 172.30.1.2

